-- Create rex_ece_evaluations table
CREATE TABLE IF NOT EXISTS rex_ece_evaluations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  entity_clarity_score INTEGER NOT NULL DEFAULT 0,
  entity_clarity_notes TEXT,
  entity_clarity_weaknesses TEXT[] DEFAULT '{}',
  consensus_score INTEGER NOT NULL DEFAULT 0,
  consensus_notes TEXT,
  consensus_conflicts TEXT[] DEFAULT '{}',
  answer_readiness_score INTEGER NOT NULL DEFAULT 0,
  answer_readiness_notes TEXT,
  answer_readiness_gaps TEXT[] DEFAULT '{}',
  risk_reduction_score INTEGER NOT NULL DEFAULT 0,
  risk_reduction_notes TEXT,
  risk_factors TEXT[] DEFAULT '{}',
  confidence_score INTEGER NOT NULL DEFAULT 0,
  confidence_notes TEXT,
  confidence_opportunities TEXT[] DEFAULT '{}',
  weakest_pillar TEXT,
  evaluation_data JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_rex_evaluations_business ON rex_ece_evaluations(business_id);
CREATE INDEX idx_rex_evaluations_user ON rex_ece_evaluations(user_id);
CREATE INDEX idx_rex_evaluations_created ON rex_ece_evaluations(created_at DESC);

COMMENT ON TABLE rex_ece_evaluations IS 'Rex ECE (Entity Confidence Engine) evaluations per business';

-- Create rex_recommendations table
CREATE TABLE IF NOT EXISTS rex_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  evaluation_id UUID REFERENCES rex_ece_evaluations(id) ON DELETE SET NULL,
  target_pillar TEXT NOT NULL,
  action_type TEXT NOT NULL,
  title TEXT NOT NULL,
  explanation TEXT NOT NULL,
  exact_copy TEXT,
  application_location TEXT,
  expected_impact TEXT,
  estimated_minutes INTEGER,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent_to_admin', 'sent_to_customer', 'approved', 'in_progress', 'completed', 'declined')),
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE INDEX idx_rex_recommendations_business ON rex_recommendations(business_id);
CREATE INDEX idx_rex_recommendations_status ON rex_recommendations(status);

COMMENT ON TABLE rex_recommendations IS 'Actionable recommendations generated by Rex for weakest pillar';

-- Create visibility_score_details table
CREATE TABLE IF NOT EXISTS visibility_score_details (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  score_date DATE NOT NULL,
  overall_score INTEGER NOT NULL DEFAULT 0,
  profile_completeness_score INTEGER DEFAULT 0,
  review_quality_score INTEGER DEFAULT 0,
  citation_presence_score INTEGER DEFAULT 0,
  content_relevance_score INTEGER DEFAULT 0,
  technical_seo_score INTEGER DEFAULT 0,
  social_presence_score INTEGER DEFAULT 0,
  benchmark_percentile INTEGER,
  month_over_month_change INTEGER,
  recommendations JSONB DEFAULT '[]',
  pillar_scores JSONB DEFAULT '{}',
  calculation_metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(business_id, score_date)
);

CREATE INDEX idx_visibility_scores_business ON visibility_score_details(business_id);
CREATE INDEX idx_visibility_scores_date ON visibility_score_details(score_date DESC);

COMMENT ON TABLE visibility_score_details IS 'Detailed visibility scores across 8 dimensions with benchmarks';

-- Create monthly_competitor_analysis table
CREATE TABLE IF NOT EXISTS monthly_competitor_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tier TEXT NOT NULL DEFAULT 'professional' CHECK (tier IN ('basic', 'professional', 'enterprise')),
  month TEXT NOT NULL,
  year INTEGER NOT NULL,
  your_business JSONB DEFAULT '{}',
  top_competitors JSONB DEFAULT '[]',
  blind_spots JSONB DEFAULT '[]',
  quick_fixes JSONB DEFAULT '[]',
  tier_features JSONB DEFAULT '{}',
  generated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_monthly_analysis_business ON monthly_competitor_analysis(business_id);
CREATE INDEX idx_monthly_analysis_date ON monthly_competitor_analysis(year DESC, month DESC);

COMMENT ON TABLE monthly_competitor_analysis IS 'Monthly competitor analysis reports per tier';

-- RLS Policies
ALTER TABLE rex_ece_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE rex_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE visibility_score_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_competitor_analysis ENABLE ROW LEVEL SECURITY;

-- Users can view their own data
CREATE POLICY "Users view own rex evaluations"
  ON rex_ece_evaluations FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users view own rex recommendations"
  ON rex_recommendations FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users view own visibility scores"
  ON visibility_score_details FOR SELECT
  USING (business_id IN (
    SELECT id FROM businesses WHERE user_id = auth.uid()
  ));

CREATE POLICY "Users view own competitor analysis"
  ON monthly_competitor_analysis FOR SELECT
  USING (user_id = auth.uid());

-- Service role can manage all
CREATE POLICY "Service role manages rex evaluations"
  ON rex_ece_evaluations FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role manages rex recommendations"
  ON rex_recommendations FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role manages visibility scores"
  ON visibility_score_details FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role manages competitor analysis"
  ON monthly_competitor_analysis FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
